
[licenses]
allow = ["MIT", "Apache-2.0"]
copyleft = "deny"
confidence-threshold = 1.0

exceptions = []

[bans]
multiple-versions = "deny"
wildcards = "warn"

[sources]
unknown-git = "deny"

[sources.allow-org]
github = ["amethyst", "radium-io"]
